PERF_API_URL: "http://localhost/v2/api/cicd/"
api_timeout: 2
api_params: 
 sla: 
  pageLoadTime: 2000
 baseline: 
  days: 7
  perc: 75
  padding: 1.2
 flags: 
  assertBaseline: true
  debug: false
  esTrace: false
  esCreate: false
  passOnFailedAssert: false
 log: 
  test_info: "Sample test_info"
  env_tester: "Sample tester"
  browser: "Sample browser"
  env_target: "Sample target"
  team: "SAMPLE TEAM"